[emal notifications] adding tal namespace directive to all email templates - resolves exception in notification callback for some types.
Resolves this error:
BungeniCustomError: XMLSyntaxError: Namespace prefix tal for replace on span is not defined, line 5, column 52...
[in bungeni.core.emailnotifications.email_notifications_callback]

- Removing metal namespace directive (unused)